version: '2'
services:
  jenkins:
    build: .
    container_name: jenkins-master
    ports:
      - "80:8080"
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    volumes:
      - ./groovy/executors.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy
      - ./custom/custom.groovy:/usr/share/jenkins/ref/init.groovy.d/custom.groovy
      - ./logging/log.properties:/var/jenkins_home/log.properties
      - /jenkins_home:/var/jenkins_home
